### ISSUE TITLE
RuntimeError: CUDA error: invalid device ordinal

### ISSUE THREAD

**Issue by JKYtydt** [KimMeen/Time-LLM#45]
运行脚本时，提示无效的设备序号，我是用CUDA_VISIBLE_DEVICES这个设置了GPU设备，请问怎么解决，期待您的回复

**Comment by JKYtydt** [comment]
上个问题解决了，但出现了新问题：
Traceback (most recent call last):
  File "/sdc/jky/Time-LLM/run_main.py", line 211, in <module>
    outputs = model(batch_x, batch_x_mark, dec_inp, batch_y_mark)
  File "/data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1852, in forward
    loss = self.module(*inputs, **kwargs)
  File "/data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/sdc/jky/Time-LLM/models/TimeLLM.py", line 198, in forward
    dec_out = self.forecast(x_enc, x_mark_enc, x_dec, x_mark_dec)
  File "/sdc/jky/Time-LLM/models/TimeLLM.py", line 237, in forecast
    prompt_embeddings = self.llm_model.get_input_embeddings()(prompt.to(x_enc.device))  # (batch, prompt_token, dim)
  File "/data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/torch/nn/modules/sparse.py", line 163, in forward
    return F.embedding(
  File "/data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/torch/nn/functional.py", line 2237, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by nitinnat** [comment]
I'm facing the same issue.

**Comment by kwuking** [comment]
> 上个问题解决了，但出现了新问题： Traceback (most recent call last): File "/sdc/jky/Time-LLM/run_main.py", line 211, in outputs = model(batch_x, batch_x_mark, dec_inp, batch_y_mark) File "/data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl return forward_call(*args, **kwargs) File "/data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn ret_val = func(*args, **kwargs) File "/data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1852, in forward loss = self.module(*inputs, **kwargs) File "/data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl return forward_call(*args, **kwargs) File "/sdc/jky/Time-LLM/models/TimeLLM.py", line 198, in forward dec_out = self.forecast(x_enc, x_mark_enc, x_dec, x_mark_dec) File "/sdc/jky/Time-LLM/models/TimeLLM.py", line 237, in forecast prompt_embeddings = self.llm_model.get_input_embeddings()(prompt.to(x_enc.device)) # (batch, prompt_token, dim) File "/data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl return forward_call(*args, **kwargs) File "/data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/torch/nn/modules/sparse.py", line 163, in forward return F.embedding( File "/data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/torch/nn/functional.py", line 2237, in embedding return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse) RuntimeError: CUDA error: device-side assert triggered Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

hi, the current model is trained using the accelerator framework for distributed training. If you want to run it on a single GPU, you need to remove the dependencies related to the accelerator framework.

**Comment by JKYtydt** [comment]
> > 上一个问题解决了，但出现了新问题： Traceback (most最近一次调用最后): File "/sdc/jky/Time-LLM/run_main.py", line 211, inoutputs = model(batch_x, batch_x_mark, dec_inp, batch_y_mark）文件“/data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/torch/nn/modules/module.py”，第1511行，在_wrapped_call_impl中返回self._call_impl（*args，**kwargs ）文件“/data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/torch/nn/modules/module.py”，第1520行，在_call_impl中返回forward_call（*args，**kwargs）文件“ /data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/deepspeed/utils/nvtx.py”，第 15 行，位于wrapped_fn ret_val = func(*args，**kwargs) 文件“/data/anaconda3 /envs/jky_pt/lib/python3.9/site-packages/deepspeed/runtime/engine.py”，第 1852 行，前向损耗 = self.module(*inputs, **kwargs) 文件“/data/anaconda3/envs /jky_pt/lib/python3.9/site-packages/torch/nn/modules/module.py”，第 1511 行，在 _wrapped_call_impl 返回 self._call_impl(*args, **kwargs) 文件“/data/anaconda3/envs/ jky_pt/lib/python3.9/site-packages/torch/nn/modules/module.py”，第 1520 行，在 _call_impl 返回forward_call(*args, **kwargs) 文件“/sdc/jky/Time-LLM/models /TimeLLM.py”，第 198 行，在正向 dec_out = self.forecast(x_enc, x_mark_enc, x_dec, x_mark_dec) 文件“/sdc/jky/Time-LLM/models/TimeLLM.py”，第 237 行，在预测中 prompt_embeddings = self.llm_model.get_input_embeddings()(prompt.to(x_enc.device)) # (batch,prompt_token,dim) 文件“/data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/torch/nn/ module/module.py”，第 1511 行，在 _wrapped_call_impl 返回 self._call_impl(*args, **kwargs) 文件“/data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/torch/nn/modules /module.py”，第 1520 行，在 _call_impl 返回forward_call(*args, **kwargs) 文件“/data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/torch/nn/modules/sparse. py"，第 163 行，在正向返回中 F.embedding( File "/data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/torch/nn/function.py"，第 2237 行，在嵌入返回 torch 中.embedding（weight，input，padding_idx，scale_grad_by_freq，sparse）RuntimeError：CUDA错误：设备端断言触发编译以`TORCH_USE_CUDA_DSA`启用设备端断言。
> 
> 您好，当前模型是使用分布式训练加速器框架进行训练的。如果你想在单个GPU上运行它，你需要删除与加速器框架相关的依赖项。

您好，我是在多GPU运行的，现在这个无效设备号解决了，出现了新的问题RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`

**Comment by kwuking** [comment]
> RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`

这个报错表示在调用cublasCreate(handle)时出现CUDA错误：CUBLAS_STATUS_ALLOC_FAILED。这通常意味着在尝试为cuBLAS创建句柄时内存分配失败。可能的原因包括GPU内存不足或者其他GPU资源限制导致无法分配所需的内存。要解决此问题，您可以尝试减少GPU上的内存占用，优化代码以减少内存需求，或者考虑在具有更多GPU内存的环境中运行代码。

**Comment by kwuking** [comment]
> > > 上一个问题解决了，但出现了新问题： Traceback (most最近一次调用最后): File "/sdc/jky/Time-LLM/run_main.py", line 211, inoutputs = model(batch_x, batch_x_mark, dec_inp, batch_y_mark）文件“/data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/torch/nn/modules/module.py”，第1511行，在_wrapped_call_impl中返回self._call_impl（*args，**kwargs ）文件“/data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/torch/nn/modules/module.py”，第1520行，在_call_impl中返回forward_call（*args，**kwargs）文件“ /data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/deepspeed/utils/nvtx.py”，第 15 行，位于wrapped_fn ret_val = func(*args，**kwargs) 文件“/data/anaconda3 /envs/jky_pt/lib/python3.9/site-packages/deepspeed/runtime/engine.py”，第 1852 行，前向损耗 = self.module(*inputs, **kwargs) 文件“/data/anaconda3/envs /jky_pt/lib/python3.9/site-packages/torch/nn/modules/module.py”，第 1511 行，在 _wrapped_call_impl 返回 self._call_impl(*args, **kwargs) 文件“/data/anaconda3/envs/ jky_pt/lib/python3.9/site-packages/torch/nn/modules/module.py”，第 1520 行，在 _call_impl 返回forward_call(*args, **kwargs) 文件“/sdc/jky/Time-LLM/models /TimeLLM.py”，第 198 行，在正向 dec_out = self.forecast(x_enc, x_mark_enc, x_dec, x_mark_dec) 文件“/sdc/jky/Time-LLM/models/TimeLLM.py”，第 237 行，在预测中 prompt_embeddings = self.llm_model.get_input_embeddings()(prompt.to(x_enc.device)) # (batch,prompt_token,dim) 文件“/data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/torch/nn/ module/module.py”，第 1511 行，在 _wrapped_call_impl 返回 self._call_impl(*args, **kwargs) 文件“/data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/torch/nn/modules /module.py”，第 1520 行，在 _call_impl 返回forward_call(*args, **kwargs) 文件“/data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/torch/nn/modules/sparse. py"，第 163 行，在正向返回中 F.embedding( File "/data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/torch/nn/function.py"，第 2237 行，在嵌入返回 torch 中.embedding（weight，input，padding_idx，scale_grad_by_freq，sparse）RuntimeError：CUDA错误：设备端断言触发编译以`TORCH_USE_CUDA_DSA`启用设备端断言。
> > 
> > 
> > 您好，当前模型是使用分布式训练加速器框架进行训练的。如果你想在单个GPU上运行它，你需要删除与加速器框架相关的依赖项。
> 
> 您好，我是在多GPU运行的，现在这个无效设备号解决了，出现了新的问题RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`

我们目前使用的A100 80G，您可以参考，建议使用大显存GPU，或者减少LLAMA层数，或者替换成GPT2等相对较小的模型。

**Comment by JKYtydt** [comment]
> > 上一个问题解决了，但出现了新问题： Traceback (most最近一次调用最后): File "/sdc/jky/Time-LLM/run_main.py", line 211, inoutputs = model(batch_x, batch_x_mark, dec_inp, batch_y_mark）文件“/data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/torch/nn/modules/module.py”，第1511行，在_wrapped_call_impl中返回self._call_impl（*args，**kwargs ）文件“/data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/torch/nn/modules/module.py”，第1520行，在_call_impl中返回forward_call（*args，**kwargs）文件“ /data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/deepspeed/utils/nvtx.py”，第 15 行，位于wrapped_fn ret_val = func(*args，**kwargs) 文件“/data/anaconda3 /envs/jky_pt/lib/python3.9/site-packages/deepspeed/runtime/engine.py”，第 1852 行，前向损耗 = self.module(*inputs, **kwargs) 文件“/data/anaconda3/envs /jky_pt/lib/python3.9/site-packages/torch/nn/modules/module.py”，第 1511 行，在 _wrapped_call_impl 返回 self._call_impl(*args, **kwargs) 文件“/data/anaconda3/envs/ jky_pt/lib/python3.9/site-packages/torch/nn/modules/module.py”，第 1520 行，在 _call_impl 返回forward_call(*args, **kwargs) 文件“/sdc/jky/Time-LLM/models /TimeLLM.py”，第 198 行，在正向 dec_out = self.forecast(x_enc, x_mark_enc, x_dec, x_mark_dec) 文件“/sdc/jky/Time-LLM/models/TimeLLM.py”，第 237 行，在预测中 prompt_embeddings = self.llm_model.get_input_embeddings()(prompt.to(x_enc.device)) # (batch,prompt_token,dim) 文件“/data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/torch/nn/ module/module.py”，第 1511 行，在 _wrapped_call_impl 返回 self._call_impl(*args, **kwargs) 文件“/data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/torch/nn/modules /module.py”，第 1520 行，在 _call_impl 返回forward_call(*args, **kwargs) 文件“/data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/torch/nn/modules/sparse. py"，第 163 行，在正向返回中 F.embedding( File "/data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/torch/nn/function.py"，第 2237 行，在嵌入返回 torch 中.embedding（weight，input，padding_idx，scale_grad_by_freq，sparse）RuntimeError：CUDA错误：设备端断言触发编译以`TORCH_USE_CUDA_DSA`启用设备端断言。
> 
> 您好，当前模型是使用分布式训练加速器框架进行训练的。如果你想在单个GPU上运行它，你需要删除与加速器框架相关的依赖项。

您好，我是用--gpu_ids 0,5,6这个参数解决设备序号无效这个问题的，但是当我指定两个GPU时--gpu_ids 0,5，依然会报设备序号无效这个错误，您知道这个原因么

**Comment by kwuking** [comment]
> > > 上一个问题解决了，但出现了新问题： Traceback (most最近一次调用最后): File "/sdc/jky/Time-LLM/run_main.py", line 211, inoutputs = model(batch_x, batch_x_mark, dec_inp, batch_y_mark）文件“/data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/torch/nn/modules/module.py”，第1511行，在_wrapped_call_impl中返回self._call_impl（*args，**kwargs ）文件“/data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/torch/nn/modules/module.py”，第1520行，在_call_impl中返回forward_call（*args，**kwargs）文件“ /data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/deepspeed/utils/nvtx.py”，第 15 行，位于wrapped_fn ret_val = func(*args，**kwargs) 文件“/data/anaconda3 /envs/jky_pt/lib/python3.9/site-packages/deepspeed/runtime/engine.py”，第 1852 行，前向损耗 = self.module(*inputs, **kwargs) 文件“/data/anaconda3/envs /jky_pt/lib/python3.9/site-packages/torch/nn/modules/module.py”，第 1511 行，在 _wrapped_call_impl 返回 self._call_impl(*args, **kwargs) 文件“/data/anaconda3/envs/ jky_pt/lib/python3.9/site-packages/torch/nn/modules/module.py”，第 1520 行，在 _call_impl 返回forward_call(*args, **kwargs) 文件“/sdc/jky/Time-LLM/models /TimeLLM.py”，第 198 行，在正向 dec_out = self.forecast(x_enc, x_mark_enc, x_dec, x_mark_dec) 文件“/sdc/jky/Time-LLM/models/TimeLLM.py”，第 237 行，在预测中 prompt_embeddings = self.llm_model.get_input_embeddings()(prompt.to(x_enc.device)) # (batch,prompt_token,dim) 文件“/data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/torch/nn/ module/module.py”，第 1511 行，在 _wrapped_call_impl 返回 self._call_impl(*args, **kwargs) 文件“/data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/torch/nn/modules /module.py”，第 1520 行，在 _call_impl 返回forward_call(*args, **kwargs) 文件“/data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/torch/nn/modules/sparse. py"，第 163 行，在正向返回中 F.embedding( File "/data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/torch/nn/function.py"，第 2237 行，在嵌入返回 torch 中.embedding（weight，input，padding_idx，scale_grad_by_freq，sparse）RuntimeError：CUDA错误：设备端断言触发编译以`TORCH_USE_CUDA_DSA`启用设备端断言。
> > 
> > 
> > 您好，当前模型是使用分布式训练加速器框架进行训练的。如果你想在单个GPU上运行它，你需要删除与加速器框架相关的依赖项。
> 
> 您好，我是用--gpu_ids 0,5,6这个参数解决设备序号无效这个问题的，但是当我指定两个GPU时--gpu_ids 0,5，依然会报设备序号无效这个错误，您知道这个原因么

请问num_process有修改成对应的gpu数量嘛，可以使用nvidia命令查看下gpu状态，确保没有问题。

**Comment by Farsalrio** [comment]
> > > > 上一个问题解决了，但出现了新问题： Traceback (most最近一次调用最后): File "/sdc/jky/Time-LLM/run_main.py", line 211, inoutputs = model(batch_x, batch_x_mark, dec_inp, batch_y_mark）文件“/data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/torch/nn/modules/module.py”，第1511行，在_wrapped_call_impl中返回self._call_impl（*args，**kwargs ）文件“/data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/torch/nn/modules/module.py”，第1520行，在_call_impl中返回forward_call（*args，**kwargs）文件“ /data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/deepspeed/utils/nvtx.py”，第 15 行，位于wrapped_fn ret_val = func(*args，**kwargs) 文件“/data/anaconda3 /envs/jky_pt/lib/python3.9/site-packages/deepspeed/runtime/engine.py”，第 1852 行，前向损耗 = self.module(*inputs, **kwargs) 文件“/data/anaconda3/envs /jky_pt/lib/python3.9/site-packages/torch/nn/modules/module.py”，第 1511 行，在 _wrapped_call_impl 返回 self._call_impl(*args, **kwargs) 文件“/data/anaconda3/envs/ jky_pt/lib/python3.9/site-packages/torch/nn/modules/module.py”，第 1520 行，在 _call_impl 返回forward_call(*args, **kwargs) 文件“/sdc/jky/Time-LLM/models /TimeLLM.py”，第 198 行，在正向 dec_out = self.forecast(x_enc, x_mark_enc, x_dec, x_mark_dec) 文件“/sdc/jky/Time-LLM/models/TimeLLM.py”，第 237 行，在预测中 prompt_embeddings = self.llm_model.get_input_embeddings()(prompt.to(x_enc.device)) # (batch,prompt_token,dim) 文件“/data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/torch/nn/ module/module.py”，第 1511 行，在 _wrapped_call_impl 返回 self._call_impl(*args, **kwargs) 文件“/data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/torch/nn/modules /module.py”，第 1520 行，在 _call_impl 返回forward_call(*args, **kwargs) 文件“/data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/torch/nn/modules/sparse. py"，第 163 行，在正向返回中 F.embedding( File "/data/anaconda3/envs/jky_pt/lib/python3.9/site-packages/torch/nn/function.py"，第 2237 行，在嵌入返回 torch 中.embedding（weight，input，padding_idx，scale_grad_by_freq，sparse）RuntimeError：CUDA错误：设备端断言触发编译以`TORCH_USE_CUDA_DSA`启用设备端断言。
> > > 
> > > 
> > > 您好，当前模型是使用分布式训练加速器框架进行训练的。如果你想在单个GPU上运行它，你需要删除与加速器框架相关的依赖项。
> > 
> > 
> > 您好，我是用--gpu_ids 0,5,6这个参数解决设备序号无效这个问题的，但是当我指定两个GPU时--gpu_ids 0,5，依然会报设备序号无效这个错误，您知道这个原因么
> 
> 请问num_process有修改成对应的gpu数量嘛，可以使用nvidia命令查看下gpu状态，确保没有问题。

Can we run the experiments on google colab with 15GB RAM? If yes can you help me on how to do?
